# Generated by Django 5.1.1 on 2024-12-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='otp_code',
            field=models.CharField(max_length=4),
        ),
    ]
