# Generated by Django 5.1.1 on 2024-09-29 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_count', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_scores', to='api.event')),
                ('user_event_voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_scores', to='api.usereventvoting')),
            ],
            options={
                'unique_together': {('event', 'user_event_voting')},
            },
        ),
    ]
