# Generated by Django 5.1.1 on 2024-09-29 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_votescore'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='votescore',
            unique_together=set(),
        ),
    ]
