# Generated by Django 5.1.1 on 2024-09-30 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_votescore_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='votescore',
            unique_together={('event', 'user_event_voting')},
        ),
    ]
