# Generated by Django 5.1.1 on 2024-09-30 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_votescore_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='votescore',
            unique_together=set(),
        ),
    ]
