# Generated by Django 5.1.1 on 2024-11-21 07:30

import ckeditor.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_category_options_category_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestTermConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorized_signature', models.ImageField(blank=True, null=True, upload_to='contest_authorized_signature')),
                ('terms_conditions', ckeditor.fields.RichTextField()),
                ('approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestant_photo', models.ImageField(upload_to='contestant_image')),
                ('contestant_first_name', models.CharField(max_length=50)),
                ('contestant_last_name', models.CharField(max_length=50)),
                ('contestant_dob', models.DateField()),
                ('contestant_city', models.CharField(max_length=100)),
                ('contestant_age', models.PositiveIntegerField()),
                ('contestant_mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('contestant_whatsapp_no', models.CharField(blank=True, max_length=15, null=True)),
                ('contestant_email', models.EmailField(max_length=254, unique=True)),
                ('contestant_school_name', models.CharField(max_length=100)),
                ('contestant_class', models.CharField(max_length=50)),
                ('contestant_father_name', models.CharField(max_length=100)),
                ('contestant_mother_name', models.CharField(max_length=100)),
                ('contestant_previous_performance', models.BooleanField(default=False)),
                ('contestant_no', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('contest_start_date', models.DateField(blank=True, null=True)),
                ('contest_end_date', models.DateField(blank=True, null=True)),
                ('contest_status', models.BooleanField(default=False)),
                ('contest_category', models.CharField(choices=[('dancing', 'Dancing'), ('singing', 'Singing'), ('acting/comedy', 'Acting/Comedy'), ('drawing', 'Drawing'), ('others', 'Others')], default='others', max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_user', to=settings.AUTH_USER_MODEL)),
                ('contest_terms_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_terms_condition', to='api.contesttermconditions')),
            ],
        ),
    ]
