# Generated by Django 5.1.1 on 2024-11-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_contesttermconditions_contest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contesttermconditions',
            name='authorized_signature',
        ),
        migrations.AlterField(
            model_name='contest',
            name='contestant_no',
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='contestant_photo',
            field=models.ImageField(null=True, upload_to='contestant_image'),
        ),
    ]
