# Generated by Django 5.1.1 on 2024-11-21 10:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_contesttermconditions_authorized_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contesttermconditions',
            name='authorized_signature',
            field=models.ImageField(blank=True, null=True, upload_to='contest_authorized_signature'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='contestant_no',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
