# Generated by Django 5.1.1 on 2024-11-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_contesttermconditions_authorized_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contestant_no',
            field=models.IntegerField(),
        ),
    ]
