# Generated by Django 5.1.1 on 2024-11-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_contest_contestant_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contestant_no',
            field=models.IntegerField(default=None),
        ),
    ]
