# Generated by Django 5.1.1 on 2024-11-22 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_contestantfollow_contestantlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='contest_end_date',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='contest_start_date',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='contest_status',
        ),
    ]
