# Generated by Django 5.1.1 on 2024-11-22 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_contest_contest_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='api.event'),
            preserve_default=False,
        ),
    ]
