# Generated by Django 5.1.1 on 2024-11-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_contestphoto_contestvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contest_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='contest_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='contest_status',
            field=models.BooleanField(default=False),
        ),
    ]
