# Generated by Django 5.1.1 on 2024-11-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_event_contest_end_time_event_contest_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='contest_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
