# Generated by Django 5.1.1 on 2024-11-24 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_contest_contest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventvotingsettings',
            name='voting_list',
        ),
        migrations.AddField(
            model_name='eventvotingsettings',
            name='contest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contest', to='api.contest'),
            preserve_default=False,
        ),
    ]
