# Generated by Django 5.1.1 on 2024-11-24 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_eventvotingsettings_voting_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventvotingsettings',
            name='contest',
        ),
    ]
