# Generated by Django 5.1.1 on 2024-11-24 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_eventvotingsettings_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereventvoting',
            name='contest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contest', to='api.contest'),
            preserve_default=False,
        ),
    ]
