# Generated by Django 5.1.1 on 2024-11-29 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_eventcontestantfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcontestantfield',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AdsRelatedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the video', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Brief description of the video content', null=True)),
                ('video_url', models.URLField(help_text='URL of the video')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when the video was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time when the video was last updated')),
                ('duration_in_seconds', models.IntegerField(blank=True, help_text='Duration of the video in seconds', null=True)),
                ('ad', models.ForeignKey(help_text='The ad campaign this video is related to', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.add')),
            ],
            options={
                'verbose_name': 'Ads Related Video',
                'verbose_name_plural': 'Ads Related Videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
