# Generated by Django 5.1.1 on 2024-11-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_eventcontestantfield_status_adsrelatedvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideosForYou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the video', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the video', null=True)),
                ('video_url', models.URLField(help_text='URL of the video')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the video was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the video was last updated')),
            ],
            options={
                'verbose_name': 'Video for You',
                'verbose_name_plural': 'Videos for You',
                'ordering': ['-created_at'],
            },
        ),
    ]
