# Generated by Django 5.1.1 on 2024-12-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_videosforyou'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestvideo',
            name='video_title',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
