# Generated by Django 5.1.1 on 2024-12-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_contestvideo_video_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsrelatedvideo',
            name='title',
        ),
        migrations.AddField(
            model_name='add',
            name='title',
            field=models.CharField(default=3, help_text='Title of the Ads', max_length=255),
            preserve_default=False,
        ),
    ]
