# Generated by Django 5.1.1 on 2024-12-15 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_adsrelatedvideo_title_add_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('PREMIUM', 'Premium Entry'), ('VIP', 'VIP Entry'), ('PREMIUM_VIP', 'Premium VIP Entry')], default='PREMIUM', help_text='Select the type of ticket', max_length=15)),
                ('price_per_ticket', models.DecimalField(decimal_places=2, help_text='Price of the ticket (e.g., 1234.56)', max_digits=6)),
                ('total_ticket_count', models.PositiveIntegerField(help_text='Total number of tickets available')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium_ticket_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('vip_ticket_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('premium_vip_ticket_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, help_text='Total price of the ticket with premium + VIP + premium VIP prices', max_digits=10)),
                ('full_name', models.CharField(help_text='Enter Your Name', max_length=255)),
                ('address', models.CharField(help_text='Enter Your Address', max_length=255)),
                ('contact_number', models.CharField(help_text='Enter Your Contact Number', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_tickets', to='api.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_tickets', to=settings.AUTH_USER_MODEL)),
                ('premium_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premium_bookings', to='api.createticket')),
                ('premium_vip_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premium_vip_bookings', to='api.createticket')),
                ('vip_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vip_bookings', to='api.createticket')),
            ],
        ),
    ]
