# Generated by Django 5.1.1 on 2024-12-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_createticket_bookticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createticket',
            name='ticket_type',
            field=models.CharField(choices=[('PREMIUM', 'Premium Entry'), ('VIP', 'VIP Entry'), ('PREMIUM_VIP', 'Premium VIP Entry')], help_text='Select the type of ticket', max_length=15),
        ),
    ]
