# Generated by Django 5.1.1 on 2024-12-15 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_createticket_ticket_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookticket',
            old_name='event',
            new_name='event_id',
        ),
    ]
